#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'T2HMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 18

# The Active Message type associated with this message.
AM_TYPE = 8

class T2HMsg(tinyos.message.Message.Message):
    # Create a new T2HMsg of size 18.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=18):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <T2HMsg> \n"
        try:
            s += "  [ACKs=";
            for i in range(0, 8):
                s += "0x%x " % (self.getElement_ACKs(i) & 0xffff)
            s += "]\n";
        except:
            pass
        try:
            s += "  [transmission=0x%x]\n" % (self.get_transmission())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: ACKs
    #   Field type: int[]
    #   Offset (bits): 0
    #   Size of each element (bits): 16
    #

    #
    # Return whether the field 'ACKs' is signed (False).
    #
    def isSigned_ACKs(self):
        return False
    
    #
    # Return whether the field 'ACKs' is an array (True).
    #
    def isArray_ACKs(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'ACKs'
    #
    def offset_ACKs(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 16
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'ACKs'
    #
    def offsetBits_ACKs(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 16
        return offset
    
    #
    # Return the entire array 'ACKs' as a int[]
    #
    def get_ACKs(self):
        tmp = [None]*8
        for index0 in range (0, self.numElements_ACKs(0)):
                tmp[index0] = self.getElement_ACKs(index0)
        return tmp
    
    #
    # Set the contents of the array 'ACKs' from the given int[]
    #
    def set_ACKs(self, value):
        for index0 in range(0, len(value)):
            self.setElement_ACKs(index0, value[index0])

    #
    # Return an element (as a int) of the array 'ACKs'
    #
    def getElement_ACKs(self, index1):
        return self.getUIntElement(self.offsetBits_ACKs(index1), 16, 1)
    
    #
    # Set an element of the array 'ACKs'
    #
    def setElement_ACKs(self, index1, value):
        self.setUIntElement(self.offsetBits_ACKs(index1), 16, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'ACKs'
    #
    def totalSize_ACKs(self):
        return (128 / 8)
    
    #
    # Return the total size, in bits, of the array 'ACKs'
    #
    def totalSizeBits_ACKs(self):
        return 128
    
    #
    # Return the size, in bytes, of each element of the array 'ACKs'
    #
    def elementSize_ACKs(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'ACKs'
    #
    def elementSizeBits_ACKs(self):
        return 16
    
    #
    # Return the number of dimensions in the array 'ACKs'
    #
    def numDimensions_ACKs(self):
        return 1
    
    #
    # Return the number of elements in the array 'ACKs'
    #
    def numElements_ACKs():
        return 8
    
    #
    # Return the number of elements in the array 'ACKs'
    # for the given dimension.
    #
    def numElements_ACKs(self, dimension):
        array_dims = [ 8,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Accessor methods for field: transmission
    #   Field type: int
    #   Offset (bits): 128
    #   Size (bits): 16
    #

    #
    # Return whether the field 'transmission' is signed (False).
    #
    def isSigned_transmission(self):
        return False
    
    #
    # Return whether the field 'transmission' is an array (False).
    #
    def isArray_transmission(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'transmission'
    #
    def offset_transmission(self):
        return (128 / 8)
    
    #
    # Return the offset (in bits) of the field 'transmission'
    #
    def offsetBits_transmission(self):
        return 128
    
    #
    # Return the value (as a int) of the field 'transmission'
    #
    def get_transmission(self):
        return self.getUIntElement(self.offsetBits_transmission(), 16, 1)
    
    #
    # Set the value of the field 'transmission'
    #
    def set_transmission(self, value):
        self.setUIntElement(self.offsetBits_transmission(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'transmission'
    #
    def size_transmission(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'transmission'
    #
    def sizeBits_transmission(self):
        return 16
    
