#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'TxSerialMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 52

# The Active Message type associated with this message.
AM_TYPE = 5

class TxSerialMsg(tinyos.message.Message.Message):
    # Create a new TxSerialMsg of size 52.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=52):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <TxSerialMsg> \n"
        try:
            s += "  [V_row=";
            for i in range(0, 8):
                s += "%f " % (self.getElement_V_row(i))
            s += "]\n";
        except:
            pass
        try:
            s += "  [data=";
            for i in range(0, 4):
                s += "%f " % (self.getElement_data(i))
            s += "]\n";
        except:
            pass
        try:
            s += "  [messageid=0x%x]\n" % (self.get_messageid())
        except:
            pass
        try:
            s += "  [current_transmission=0x%x]\n" % (self.get_current_transmission())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: V_row
    #   Field type: float[]
    #   Offset (bits): 0
    #   Size of each element (bits): 32
    #

    #
    # Return whether the field 'V_row' is signed (False).
    #
    def isSigned_V_row(self):
        return False
    
    #
    # Return whether the field 'V_row' is an array (True).
    #
    def isArray_V_row(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'V_row'
    #
    def offset_V_row(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 32
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'V_row'
    #
    def offsetBits_V_row(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 32
        return offset
    
    #
    # Return the entire array 'V_row' as a float[]
    #
    def get_V_row(self):
        tmp = [None]*8
        for index0 in range (0, self.numElements_V_row(0)):
                tmp[index0] = self.getElement_V_row(index0)
        return tmp
    
    #
    # Set the contents of the array 'V_row' from the given float[]
    #
    def set_V_row(self, value):
        for index0 in range(0, len(value)):
            self.setElement_V_row(index0, value[index0])

    #
    # Return an element (as a float) of the array 'V_row'
    #
    def getElement_V_row(self, index1):
        return self.getFloatElement(self.offsetBits_V_row(index1), 32, 0)
    
    #
    # Set an element of the array 'V_row'
    #
    def setElement_V_row(self, index1, value):
        self.setFloatElement(self.offsetBits_V_row(index1), 32, value, 0)
    
    #
    # Return the total size, in bytes, of the array 'V_row'
    #
    def totalSize_V_row(self):
        return (256 / 8)
    
    #
    # Return the total size, in bits, of the array 'V_row'
    #
    def totalSizeBits_V_row(self):
        return 256
    
    #
    # Return the size, in bytes, of each element of the array 'V_row'
    #
    def elementSize_V_row(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'V_row'
    #
    def elementSizeBits_V_row(self):
        return 32
    
    #
    # Return the number of dimensions in the array 'V_row'
    #
    def numDimensions_V_row(self):
        return 1
    
    #
    # Return the number of elements in the array 'V_row'
    #
    def numElements_V_row():
        return 8
    
    #
    # Return the number of elements in the array 'V_row'
    # for the given dimension.
    #
    def numElements_V_row(self, dimension):
        array_dims = [ 8,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Accessor methods for field: data
    #   Field type: float[]
    #   Offset (bits): 256
    #   Size of each element (bits): 32
    #

    #
    # Return whether the field 'data' is signed (False).
    #
    def isSigned_data(self):
        return False
    
    #
    # Return whether the field 'data' is an array (True).
    #
    def isArray_data(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'data'
    #
    def offset_data(self, index1):
        offset = 256
        if index1 < 0 or index1 >= 4:
            raise IndexError
        offset += 0 + index1 * 32
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'data'
    #
    def offsetBits_data(self, index1):
        offset = 256
        if index1 < 0 or index1 >= 4:
            raise IndexError
        offset += 0 + index1 * 32
        return offset
    
    #
    # Return the entire array 'data' as a float[]
    #
    def get_data(self):
        tmp = [None]*4
        for index0 in range (0, self.numElements_data(0)):
                tmp[index0] = self.getElement_data(index0)
        return tmp
    
    #
    # Set the contents of the array 'data' from the given float[]
    #
    def set_data(self, value):
        for index0 in range(0, len(value)):
            self.setElement_data(index0, value[index0])

    #
    # Return an element (as a float) of the array 'data'
    #
    def getElement_data(self, index1):
        return self.getFloatElement(self.offsetBits_data(index1), 32, 0)
    
    #
    # Set an element of the array 'data'
    #
    def setElement_data(self, index1, value):
        self.setFloatElement(self.offsetBits_data(index1), 32, value, 0)
    
    #
    # Return the total size, in bytes, of the array 'data'
    #
    def totalSize_data(self):
        return (128 / 8)
    
    #
    # Return the total size, in bits, of the array 'data'
    #
    def totalSizeBits_data(self):
        return 128
    
    #
    # Return the size, in bytes, of each element of the array 'data'
    #
    def elementSize_data(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'data'
    #
    def elementSizeBits_data(self):
        return 32
    
    #
    # Return the number of dimensions in the array 'data'
    #
    def numDimensions_data(self):
        return 1
    
    #
    # Return the number of elements in the array 'data'
    #
    def numElements_data():
        return 4
    
    #
    # Return the number of elements in the array 'data'
    # for the given dimension.
    #
    def numElements_data(self, dimension):
        array_dims = [ 4,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Accessor methods for field: messageid
    #   Field type: int
    #   Offset (bits): 384
    #   Size (bits): 16
    #

    #
    # Return whether the field 'messageid' is signed (False).
    #
    def isSigned_messageid(self):
        return False
    
    #
    # Return whether the field 'messageid' is an array (False).
    #
    def isArray_messageid(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'messageid'
    #
    def offset_messageid(self):
        return (384 / 8)
    
    #
    # Return the offset (in bits) of the field 'messageid'
    #
    def offsetBits_messageid(self):
        return 384
    
    #
    # Return the value (as a int) of the field 'messageid'
    #
    def get_messageid(self):
        return self.getUIntElement(self.offsetBits_messageid(), 16, 1)
    
    #
    # Set the value of the field 'messageid'
    #
    def set_messageid(self, value):
        self.setUIntElement(self.offsetBits_messageid(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'messageid'
    #
    def size_messageid(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'messageid'
    #
    def sizeBits_messageid(self):
        return 16
    
    #
    # Accessor methods for field: current_transmission
    #   Field type: int
    #   Offset (bits): 400
    #   Size (bits): 16
    #

    #
    # Return whether the field 'current_transmission' is signed (False).
    #
    def isSigned_current_transmission(self):
        return False
    
    #
    # Return whether the field 'current_transmission' is an array (False).
    #
    def isArray_current_transmission(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'current_transmission'
    #
    def offset_current_transmission(self):
        return (400 / 8)
    
    #
    # Return the offset (in bits) of the field 'current_transmission'
    #
    def offsetBits_current_transmission(self):
        return 400
    
    #
    # Return the value (as a int) of the field 'current_transmission'
    #
    def get_current_transmission(self):
        return self.getUIntElement(self.offsetBits_current_transmission(), 16, 1)
    
    #
    # Set the value of the field 'current_transmission'
    #
    def set_current_transmission(self, value):
        self.setUIntElement(self.offsetBits_current_transmission(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'current_transmission'
    #
    def size_current_transmission(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'current_transmission'
    #
    def sizeBits_current_transmission(self):
        return 16
    
