#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'DecodedMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 62

# The Active Message type associated with this message.
AM_TYPE = 137

class DecodedMsg(tinyos.message.Message.Message):
    # Create a new DecodedMsg of size 62.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=62):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <DecodedMsg> \n"
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [perform_svd=0x%x]\n" % (self.get_perform_svd())
        except:
            pass
        try:
            s += "  [A=";
            for i in range(0, 15):
                s += "%f " % (self.getElement_A(i))
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'counter' is signed (True).
    #
    def isSigned_counter(self):
        return True
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 8, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 8
    
    #
    # Accessor methods for field: perform_svd
    #   Field type: short
    #   Offset (bits): 8
    #   Size (bits): 8
    #

    #
    # Return whether the field 'perform_svd' is signed (True).
    #
    def isSigned_perform_svd(self):
        return True
    
    #
    # Return whether the field 'perform_svd' is an array (False).
    #
    def isArray_perform_svd(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'perform_svd'
    #
    def offset_perform_svd(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'perform_svd'
    #
    def offsetBits_perform_svd(self):
        return 8
    
    #
    # Return the value (as a short) of the field 'perform_svd'
    #
    def get_perform_svd(self):
        return self.getUIntElement(self.offsetBits_perform_svd(), 8, 1)
    
    #
    # Set the value of the field 'perform_svd'
    #
    def set_perform_svd(self, value):
        self.setUIntElement(self.offsetBits_perform_svd(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'perform_svd'
    #
    def size_perform_svd(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'perform_svd'
    #
    def sizeBits_perform_svd(self):
        return 8
    
    #
    # Accessor methods for field: A
    #   Field type: float[]
    #   Offset (bits): 16
    #   Size of each element (bits): 32
    #

    #
    # Return whether the field 'A' is signed (True).
    #
    def isSigned_A(self):
        return True
    
    #
    # Return whether the field 'A' is an array (True).
    #
    def isArray_A(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'A'
    #
    def offset_A(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 15:
            raise IndexError
        offset += 0 + index1 * 32
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'A'
    #
    def offsetBits_A(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 15:
            raise IndexError
        offset += 0 + index1 * 32
        return offset
    
    #
    # Return the entire array 'A' as a float[]
    #
    def get_A(self):
        tmp = [None]*15
        for index0 in range (0, self.numElements_A(0)):
                tmp[index0] = self.getElement_A(index0)
        return tmp
    
    #
    # Set the contents of the array 'A' from the given float[]
    #
    def set_A(self, value):
        for index0 in range(0, len(value)):
            self.setElement_A(index0, value[index0])

    #
    # Return an element (as a float) of the array 'A'
    #
    def getElement_A(self, index1):
        return self.getFloatElement(self.offsetBits_A(index1), 32, 0)
    
    #
    # Set an element of the array 'A'
    #
    def setElement_A(self, index1, value):
        self.setFloatElement(self.offsetBits_A(index1), 32, value, 0)
    
    #
    # Return the total size, in bytes, of the array 'A'
    #
    def totalSize_A(self):
        return (480 / 8)
    
    #
    # Return the total size, in bits, of the array 'A'
    #
    def totalSizeBits_A(self):
        return 480
    
    #
    # Return the size, in bytes, of each element of the array 'A'
    #
    def elementSize_A(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'A'
    #
    def elementSizeBits_A(self):
        return 32
    
    #
    # Return the number of dimensions in the array 'A'
    #
    def numDimensions_A(self):
        return 1
    
    #
    # Return the number of elements in the array 'A'
    #
    def numElements_A():
        return 15
    
    #
    # Return the number of elements in the array 'A'
    # for the given dimension.
    #
    def numElements_A(self, dimension):
        array_dims = [ 15,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
